### ISSUE TITLE
cant specify image

### ISSUE THREAD

**Issue by ghost** [jcderr/concourse-kubernetes-resource#10]
In the included file, I attempt to run a deployment with an image from a public docker hub repo. I get the following error: `cat: can't open 'docker/rucuriousyet/rapchat-api': No such file or directory`

```
jobs:
- name: deploy(rapchat-api)
  plan:
  - get: image
    trigger: true
  - put: k8s(rapchat-api)
    params:
      #Ive also tried just "rucuriousyet/rapchat-api"
      image_name: docker/rucuriousyet/rapchat-api
      image_tag: latest
```
